DROP DATABASE IF EXISTS angolar;

CREATE DATABASE angolar;

USE angolar;

CREATE TABLE products(
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL
);