// Code generated by mockery v2.23.0. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// ImageRepository is an autogenerated mock type for the ImageRepository type
type ImageRepository struct {
	mock.Mock
}

// DeleteImage provides a mock function with given fields: imageUrl
func (_m *ImageRepository) DeleteImage(imageUrl string) error {
	ret := _m.Called(imageUrl)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(imageUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveImage provides a mock function with given fields: image
func (_m *ImageRepository) SaveImage(image *multipart.FileHeader) error {
	ret := _m.Called(image)

	var r0 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) error); ok {
		r0 = rf(image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewImageRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageRepository creates a new instance of ImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageRepository(t mockConstructorTestingTNewImageRepository) *ImageRepository {
	mock := &ImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
