// Code generated by mockery v2.23.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/otaxhu/go-htmx-project/internal/models"
	mock "github.com/stretchr/testify/mock"

	wrappers "github.com/otaxhu/go-htmx-project/internal/wrappers"
)

// MockProductsRepository is an autogenerated mock type for the ProductsRepository type
type MockProductsRepository struct {
	mock.Mock
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockProductsRepository) DeleteProduct(ctx context.Context, id string) (wrappers.Tx, error) {
	ret := _m.Called(ctx, id)

	var r0 wrappers.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (wrappers.Tx, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) wrappers.Tx); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrappers.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductById provides a mock function with given fields: ctx, id
func (_m *MockProductsRepository) GetProductById(ctx context.Context, id string) (models.Product, error) {
	ret := _m.Called(ctx, id)

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: ctx, offset, limit
func (_m *MockProductsRepository) GetProducts(ctx context.Context, offset uint, limit uint) ([]models.Product, error) {
	ret := _m.Called(ctx, offset, limit)

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]models.Product, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []models.Product); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertProduct provides a mock function with given fields: ctx, product
func (_m *MockProductsRepository) UpsertProduct(ctx context.Context, product models.Product) (wrappers.Tx, error) {
	ret := _m.Called(ctx, product)

	var r0 wrappers.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) (wrappers.Tx, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) wrappers.Tx); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrappers.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockProductsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockProductsRepository creates a new instance of MockProductsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProductsRepository(t mockConstructorTestingTNewMockProductsRepository) *MockProductsRepository {
	mock := &MockProductsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
